objective:
  - Sparse support recovery
dataset:
  - simulated
  - deconvolution
  - lattice
  - portfolio
solver:
  - iht
  - l0constraint
  - l0learn
  - lars
  - omp
  - skglm
n-repetitions: 1
timeout: 60
