objective:
  - L0-penalized Least-Squares

dataset:
  - simulated[rho=0.1]

solver:
  - omp
  - iht
  - ista[adapt_lmbd=True,acceleration=True,debiasing=True]
  - l0bnb
  # - gurobi
  # - el0ps

# n-repetitions: 10
