objective:
  - Sparse linear methods

dataset:
  - simulated
  # - deconvolution
  # - libsvm[dataset=housing]

solver:
  # - omp
  # - iht
  # - ista[acceleration=True]
  # - l0bnb
  # - gurobi
  # - el0ps
  # - l0l2reg
  - omp
  - l0constraint
  # - l1l2reg

n-repetitions: 1
timeout: 60